### ISSUE TITLE
Can't get detectors to show up

### ISSUE THREAD

**Issue by smarthousetips** [JeremyDunn/homebridge-govee-water-detectors#1]
Hey there,

I tried to get this to work and I was able to get the token from the website, restarted homebridge but the detectors are not showing up.  Any advice would be great! 

I saw something about the iPhone API. Is there something I need to do to do that?

Thank you,
Kayla

**Comment by KaylaSiemon** [comment]
I have received the API key from Govee but I don't know what to do with it.  Sorry!  Very new at this. Is there somewhere I need to put it into to get the API token get. I have logged in, found the token key through the developer tools but no devices are populating.

**Comment by smarthousetips** [comment]
Please disregard. This has been resolved! Thank you!

**Comment by MattsthomeK** [comment]
I must be missing something simple here. The instructions seem anemic or presumes a level of programming language understanding that I do not possess.  
Where do I actually login to get the API token? I went thru the iOS app and requested an API key but that isn't getting me anywhere.

Any help or a direction to look for the knowledge I need to know to make these work would be awesome. Thanks for your time and thanks JeromyDunn for writing the code.
